language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

install:
  - "pip install --upgrade setuptools"
  - "pip install nose"
  - "travis_retry pip install git+git://github.com/TurboGears/crank.git"
  - "travis_retry pip install git+git://github.com/TurboGears/backlash.git"
  - "travis_retry pip install git+git://github.com/TurboGears/tg2.git@development"
  - "pip install -e .[testing]"

script: "nosetests -v"
